import { MD3LightTheme } from 'react-native-paper';

export const theme = MD3LightTheme.copyWith({
  colors: {
    primary: '#2E7D32',
    onPrimary: '#FFFFFF',
    primaryContainer: '#A5D6A7',
    onPrimaryContainer: '#1B5E20',
    secondary: '#1976D2',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#BBDEFB',
    onSecondaryContainer: '#0D47A1',
    tertiary: '#F57C00',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#FFE0B2',
    onTertiaryContainer: '#E65100',
    error: '#B3261E',
    onError: '#FFFFFF',
    errorContainer: '#F9DEDC',
    onErrorContainer: '#8C0000',
    outline: '#79747E',
    outlineVariant: '#CAC4D0',
    background: '#FAFAFA',
    onBackground: '#1C1B1F',
    surface: '#FFFBFE',
    onSurface: '#1C1B1F',
    surfaceVariant: '#ECE6F0',
    onSurfaceVariant: '#49454E',
    surfaceDim: '#DDD9E0',
    surfaceBright: '#FFFBFE',
    surfaceContainerLowest: '#FFFFFF',
    surfaceContainerLow: '#F7F2FA',
    surfaceContainer: '#F3EEF6',
    surfaceContainerHigh: '#EDE9F0',
    surfaceContainerHighest: '#E8E3EB',
    scrim: '#000000',
    inverseSurface: '#313033',
    inverseOnSurface: '#F4EFF4',
    inversePrimary: '#A5D6A7',
  },
});

export const colors = {
  primary: '#2E7D32',
  secondary: '#1976D2',
  tertiary: '#F57C00',
  error: '#B3261E',
  success: '#2E7D32',
  warning: '#F57C00',
  info: '#1976D2',
  background: '#FAFAFA',
  surface: '#FFFBFE',
  text: '#1C1B1F',
  textSecondary: '#49454E',
  textTertiary: '#79747E',
  border: '#CAC4D0',
};
